-- Do customers with kids spend more or less than customers without kids?

SELECT
	CASE
		WHEN (KIDHOME + TEENHOME) > 0 THEN 'with_kids'
		ELSE 'without_kids'
	END AS CUSTOMER_TYPE,
	ROUND(
		AVG(
			SPENDING.MNT_FRUITS + SPENDING.MNT_WINES + SPENDING.MNT_MEAT_PRODUCTS + SPENDING.MNT_FISH_PRODUCTS + SPENDING.MNT_GOLD_PRODUCTS + SPENDING.MNT_SWEET_PRODUCTS
		),
		2
	) AS AVG_SPENDING
FROM
	CUSTOMERS
	JOIN SPENDING ON CUSTOMERS.CUSTOMER_ID = SPENDING.CUSTOMER_ID
GROUP BY
	CUSTOMER_TYPE;